runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  CLOUDSQL_CONNECTION_NAME: triskitbox-158401:us-central1:triskitbox
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: 'AxbdnrC*NiYj8VRL'